addons:
  apt:
    packages:
      - graphviz
  s3_region: "eu-central-1" # Frankfurt
  artifacts:
    paths:
      - output
language: java
jdk:
  - oraclejdk8
script:
  - curl https://raw.githubusercontent.com/Factual/drake/master/bin/drake > drake
  - chmod 755 drake
  - ./drake -a guice.svg
