addons:
  apt:
    packages:
      - graphviz
  artifacts: true
    s3_region: "Frankfurt"
    paths:
      -${TRAVIS_BUILD_DIR}/output
language: java
jdk:
  - oraclejdk8
script:
  - curl https://raw.githubusercontent.com/Factual/drake/master/bin/drake > drake
  - chmod 755 drake
  - ./drake -a guice.svg
